main:
  push:
    - services:
        - docker
      imports: https://cnb.cool/TokenTeam/secrets/-/blob/main/env.yml
      stages:
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:dev .
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:dev
        - name: tcloud-cmd
          image: tencentcom/tcloud-cmd
          settings:
            secret_id: ${tencentcloud_SECRET_ID}
            secret_key: ${tencentcloud_SECRET_KEY}
            region: ap-chengdu
            instance_ids: ${server_dev_INSTANCE_ID}
            script: |
              sudo docker stop ${CNB_REPO_NAME_LOWERCASE} || true
              sudo docker rm ${CNB_REPO_NAME_LOWERCASE} || true
              sudo docker run -d --name ${CNB_REPO_NAME_LOWERCASE} \
                -p ${iwut_smartclass_backend_default_DOCKER_CONTAINER_PORT}:8080 \
                -e TZ="Asia/Shanghai" \
                -e DEBUG="${iwut_smartclass_backend_dev_DEBUG}" \
                -e DATABASE="${iwut_smartclass_backend_dev_DATABASE}" \
                -e LOG_SAVE="${iwut_smartclass_backend_dev_LOG_SAVE}" \
                -e SUMMARY_WORKER_COUNT="${iwut_smartclass_backend_default_SUMMARY_WORKER_COUNT}" \
                -e SUMMARY_QUEUE_SIZE="${iwut_smartclass_backend_default_SUMMARY_QUEUE_SIZE}" \
                -e TENCENT_SECRET_ID="${iwut_smartclass_backend_default_TENCENT_SECRET_ID}" \
                -e TENCENT_SECRET_KEY="${iwut_smartclass_backend_default_TENCENT_SECRET_KEY}" \
                -e BUCKET_URL="${iwut_smartclass_backend_default_BUCKET_URL}" \
                -e OPENAI_ENDPOINT="${iwut_smartclass_backend_default_OPENAI_ENDPOINT}" \
                -e OPENAI_KEY="${iwut_smartclass_backend_default_OPENAI_KEY}" \
                -e OPENAI_MODEL="${iwut_smartclass_backend_default_OPENAI_MODEL}" \
                -e INFO_SIMPLE="${iwut_smartclass_backend_default_INFO_SIMPLE}" \
                -e GET_WEEK_SCHEDULES="${iwut_smartclass_backend_default_GET_WEEK_SCHEDULES}" \
                -e SEARCH_LIVE_COURSE_LIST="${iwut_smartclass_backend_default_SEARCH_LIVE_COURSE_LIST}" \
                ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:dev
            query_instance: true

  tag_push:
    - services:
        - docker
      imports: https://cnb.cool/TokenTeam/secrets/-/blob/main/env.yml
      stages:
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
        - name: tcloud-cmd
          image: tencentcom/tcloud-cmd
          settings:
            secret_id: ${tencentcloud_SECRET_ID}
            secret_key: ${tencentcloud_SECRET_KEY}
            region: ap-chengdu
            instance_ids: ${server_prod_INSTANCE_ID}
            script: |
              sudo docker stop ${CNB_REPO_NAME_LOWERCASE} || true
              sudo docker rm ${CNB_REPO_NAME_LOWERCASE} || true
              sudo docker run -d --name ${CNB_REPO_NAME_LOWERCASE} \
                -p ${iwut_smartclass_backend_default_DOCKER_CONTAINER_PORT}:8080 \
                -e TZ="Asia/Shanghai" \
                -e DEBUG="${iwut_smartclass_backend_prod_DEBUG}" \
                -e DATABASE="${iwut_smartclass_backend_prod_DATABASE}" \
                -e LOG_SAVE="${iwut_smartclass_backend_prod_LOG_SAVE}" \
                -e SUMMARY_WORKER_COUNT="${iwut_smartclass_backend_default_SUMMARY_WORKER_COUNT}" \
                -e SUMMARY_QUEUE_SIZE="${iwut_smartclass_backend_default_SUMMARY_QUEUE_SIZE}" \
                -e TENCENT_SECRET_ID="${iwut_smartclass_backend_default_TENCENT_SECRET_ID}" \
                -e TENCENT_SECRET_KEY="${iwut_smartclass_backend_default_TENCENT_SECRET_KEY}" \
                -e BUCKET_URL="${iwut_smartclass_backend_default_BUCKET_URL}" \
                -e OPENAI_ENDPOINT="${iwut_smartclass_backend_default_OPENAI_ENDPOINT}" \
                -e OPENAI_KEY="${iwut_smartclass_backend_default_OPENAI_KEY}" \
                -e OPENAI_MODEL="${iwut_smartclass_backend_default_OPENAI_MODEL}" \
                -e INFO_SIMPLE="${iwut_smartclass_backend_default_INFO_SIMPLE}" \
                -e GET_WEEK_SCHEDULES="${iwut_smartclass_backend_default_GET_WEEK_SCHEDULES}" \
                -e SEARCH_LIVE_COURSE_LIST="${iwut_smartclass_backend_default_SEARCH_LIVE_COURSE_LIST}" \
                ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
            query_instance: true