name: Deploy Development Environment
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  publish:
    environment: development
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: docker setup
        uses: docker/setup-docker-action@v4.3.0
      - name: go setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
      - name: checkout
        uses: actions/checkout@v4
      - name: build go app
        run: |
          go mod download
          go build -o server ./cmd
      - name: list files
        run: ls -als
      - name: docker build
        run: |
          docker build . \
            --build-arg REPO_OWNER=${{ vars.ENV_REPO_OWNER }} \
            --build-arg REPO_NAME=${{ vars.ENV_REPO_NAME }} \
            --build-arg BRANCH=${{ vars.ENV_BRANCH }} \
            --build-arg USER_NAME=${{ secrets.ENV_USER_NAME }} \
            --build-arg PASSWORD=${{ secrets.ENV_PASSWORD }} \
            --build-arg APP_ID=${{ secrets.ENV_APP_ID }} \
            --build-arg APP_SECRET=${{ secrets.ENV_SECRET }} \
            --build-arg DOTNET_ENV=${{ vars.DOTNET_ENV }} \
            --file ${{ vars.DOCKER_FILE }} --tag ${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }}
      - name: docker tag
        run: docker tag ${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }} ${{ secrets.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }}
      - name: docker push
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }}

  deploy:
    needs: publish
    environment: development
    runs-on: sh-06_dev
    steps:
      - name: docker login
        run: |
          sudo docker login ${{ secrets.DOCKER_REGISTRY }} --username=${{ secrets.DOCKER_REGISTRY_USERNAME }} --password=${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: docker pull
        run: |
          sudo docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }}
      - name: Deploy with Docker run
        run: |
          sudo docker stop ${{ vars.DOCKER_CONTAINER_NAME }} || true
          sudo docker rm ${{ vars.DOCKER_CONTAINER_NAME }} || true
          sudo docker run -d --name ${{ vars.DOCKER_CONTAINER_NAME }} -p ${{ vars.DOCKER_CONTAINER_PORT }}:8080 ${{ secrets.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }}
          sudo docker logout ${{ secrets.DOCKER_REGISTRY }}
