name: Deploy Production Environment
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  publish:
    environment: production
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker build
        run: |
          docker build . -t ${{ vars.DOCKER_IMAGE_NAME }}
      - name: Docker tag
        run: docker tag ${{ vars.DOCKER_IMAGE_NAME }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
      - name: Docker push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
  deploy:
    needs: publish
    name: Deploy docker image
    environment: production
    runs-on: sh-05_gateway
    steps:
      - name: Docker pull
        run: |
          sudo docker pull mirror.ccs.tencentyun.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
      - name: Deploy with docker run
        run: |
          sudo docker stop ${{ vars.DOCKER_CONTAINER_NAME }} || true
          sudo docker rm ${{ vars.DOCKER_CONTAINER_NAME }} || true
          sudo docker run -d --name ${{ vars.DOCKER_CONTAINER_NAME }} \
            -p ${{ vars.DOCKER_CONTAINER_PORT }}:8080 \
            -e PORT="${{ vars.PORT }}" \
            -e DEBUG="${{ vars.DEBUG }}" \
            -e DATABASE="${{ secrets.DATABASE }}" \
            -e TENCENT_SECRET_ID="${{ secrets.TENCENT_SECRET_ID }}" \
            -e TENCENT_SECRET_KEY="${{ secrets.TENCENT_SECRET_KEY }}" \
            -e BUCKET_URL="${{ secrets.BUCKET_URL }}" \
            -e OPENAI_ENDPOINT="${{ vars.OPENAI_ENDPOINT }}" \
            -e OPENAI_KEY="${{ secrets.OPENAI_KEY }}" \
            -e OPENAI_MODEL="${{ vars.OPENAI_MODEL }}" \
            -e INFO_SIMPLE="${{ secrets.INFO_SIMPLE }}" \
            -e GET_WEEK_SCHEDULES="${{ secrets.GET_WEEK_SCHEDULES }}" \
            -e SEARCH_LIVE_COURSE_LIST="${{ secrets.SEARCH_LIVE_COURSE_LIST }}" \
            mirror.ccs.tencentyun.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
      - name: Docker image prune
        run: |
          docker image prune -a -f