name: Deploy Production Environment
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  publish:
    environment: production
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps: 
      - name: docker setup
        uses: docker/setup-docker-action@v4.3.0
      - name: docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
      - name: checkout
        uses: actions/checkout@v4
      - name: docker build
        run: |
          docker build . \
            --build-arg PORT=${{ vars.PORT }} \
            --build-arg DEBUG=${{ vars.DEBUG }} \
            --build-arg DATABASE=${{ secrets.DATABASE }} \
            --build-arg TENCENT_SECRET_ID=${{ secrets.TENCENT_SECRET_ID }} \
            --build-arg TENCENT_SECRET_KEY=${{ secrets.TENCENT_SECRET_KEY }} \
            --build-arg BUCKET_URL=${{ secrets.BUCKET_URL }} \
            --build-arg OPENAI_ENDPOINT=${{ vars.OPENAI_ENDPOINT }} \
            --build-arg OPENAI_KEY=${{ secrets.OPENAI_KEY }} \
            --build-arg OPENAI_MODEL=${{ vars.OPENAI_MODEL }} \
            --build-arg PROMPT=${{ vars.PROMPT }} \
            --file ${{ vars.DOCKER_FILE }} --tag ${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }}
      - name: docker tag
        run: docker tag ${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }} ${{ secrets.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }}
      - name: docker push
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }}
  deploy:
    needs: publish
    environment: production
    runs-on: sh-06_dev
    steps:
      - name: docker login
        run: |
          sudo docker login ${{ secrets.DOCKER_REGISTRY }} --username=${{ secrets.DOCKER_REGISTRY_USERNAME }} --password=${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: docker pull
        run: |
          sudo docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }}
      - name: Deploy with Docker run
        run: |
          sudo docker stop ${{ vars.DOCKER_CONTAINER_NAME }} || true
          sudo docker rm ${{ vars.DOCKER_CONTAINER_NAME }} || true
          sudo docker run -d --name ${{ vars.DOCKER_CONTAINER_NAME }} -p ${{ vars.DOCKER_CONTAINER_PORT }}:8080 ${{ secrets.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }}
          sudo docker logout ${{ secrets.DOCKER_REGISTRY }}